"""
oKode Frontmatter Generator — Python Files

Generates the oKode frontmatter comment block that is inserted at the top
of Python source files. This frontmatter provides at-a-glance understanding
of a file's role and runtime relationships without parsing implementation.
"""


def generate_python_frontmatter(node_data: dict, edges: list) -> str:
    """Generate oKode frontmatter comment block for a Python file.

    Args:
        node_data: Dictionary containing node metadata:
            - id (str): Unique node identifier
            - type (str): Node type (endpoint, service, task, etc.)
            - ring (str): Ring classification (ring-0, ring-1, ring-2)
            - name (str): Human-readable name
            - description (str): Brief description of what this file does
            - exports (list[str]): Exported functions/classes
            - env_vars (list[str]): Environment variables accessed
            - metadata (dict): Additional metadata (auth, retry, errors)
        edges: List of edge dictionaries:
            - type (str): Edge type (reads, writes, calls, etc.)
            - target (str): Target node name/id
            - detail (str): Specific detail about the interaction

    Returns:
        A string containing the complete frontmatter comment block,
        including the opening and closing markers.
    """
    lines = []
    lines.append("# -----------------------------------------------------------")
    lines.append("# oKode Graph Metadata — DO NOT EDIT MANUALLY")
    lines.append("# This block is auto-generated by oKode scan.")
    lines.append("# -----------------------------------------------------------")
    lines.append(f"# @okode-id:    {node_data.get('id', 'unknown')}")
    lines.append(f"# @okode-type:  {node_data.get('type', 'unknown')}")
    lines.append(f"# @okode-ring:  {node_data.get('ring', 'unknown')}")
    lines.append(f"# @okode-name:  {node_data.get('name', 'unknown')}")
    lines.append(f"# @okode-desc:  {node_data.get('description', '')}")

    # Exports
    exports = node_data.get("exports", [])
    if exports:
        lines.append(f"# @okode-exports: {', '.join(exports)}")

    # Environment variables
    env_vars = node_data.get("env_vars", [])
    if env_vars:
        lines.append(f"# @okode-env:  {', '.join(env_vars)}")

    # Metadata
    metadata = node_data.get("metadata", {})
    if metadata.get("auth_required"):
        lines.append("# @okode-auth:  required")
    if metadata.get("has_retry_logic"):
        lines.append("# @okode-retry: yes")
    error_types = metadata.get("error_types", [])
    if error_types:
        lines.append(f"# @okode-errors: {', '.join(error_types)}")

    # Edges (runtime relationships)
    if edges:
        lines.append("#")
        lines.append("# Runtime Relationships:")

        # Group edges by type for readability
        edge_groups: dict[str, list[dict]] = {}
        for edge in edges:
            edge_type = edge.get("type", "unknown")
            if edge_type not in edge_groups:
                edge_groups[edge_type] = []
            edge_groups[edge_type].append(edge)

        for edge_type, group in sorted(edge_groups.items()):
            for edge in group:
                target = edge.get("target", "unknown")
                detail = edge.get("detail", "")
                if detail:
                    lines.append(f"#   --{edge_type}--> {target}  ({detail})")
                else:
                    lines.append(f"#   --{edge_type}--> {target}")

    lines.append("# -----------------------------------------------------------")
    lines.append("")

    return "\n".join(lines)


def strip_existing_frontmatter(source: str) -> str:
    """Remove existing oKode frontmatter from a Python source string.

    Args:
        source: The full source code of the Python file.

    Returns:
        The source code with oKode frontmatter removed.
    """
    lines = source.split("\n")
    result_lines = []
    in_frontmatter = False

    for line in lines:
        if line.startswith("# ---------") and "oKode Graph Metadata" in (
            lines[lines.index(line) + 1] if lines.index(line) + 1 < len(lines) else ""
        ):
            in_frontmatter = True
            continue
        if in_frontmatter:
            if line.startswith("# ---------") and not line.strip().endswith(
                "oKode Graph Metadata"
            ):
                in_frontmatter = False
                continue
            continue
        result_lines.append(line)

    return "\n".join(result_lines)


def inject_frontmatter(source: str, node_data: dict, edges: list) -> str:
    """Inject or replace oKode frontmatter in a Python source file.

    If existing frontmatter is present, it is replaced. Otherwise, the
    frontmatter is prepended to the file, preserving any shebang line
    or encoding declaration.

    Args:
        source: The full source code of the Python file.
        node_data: Node metadata dictionary (see generate_python_frontmatter).
        edges: List of edge dictionaries (see generate_python_frontmatter).

    Returns:
        The source code with updated oKode frontmatter.
    """
    # Strip existing frontmatter first
    clean_source = strip_existing_frontmatter(source)
    frontmatter = generate_python_frontmatter(node_data, edges)

    # Preserve shebang and encoding lines
    lines = clean_source.split("\n")
    prefix_lines = []
    body_start = 0

    for i, line in enumerate(lines):
        if i == 0 and line.startswith("#!"):
            prefix_lines.append(line)
            body_start = i + 1
        elif i <= 1 and line.startswith("# -*- coding"):
            prefix_lines.append(line)
            body_start = i + 1
        else:
            break

    body = "\n".join(lines[body_start:]).lstrip("\n")
    parts = []
    if prefix_lines:
        parts.append("\n".join(prefix_lines))
        parts.append("")
    parts.append(frontmatter)
    if body:
        parts.append(body)

    return "\n".join(parts)
